name = "CifAPI"
uuid = "9ad20fd4-a8ba-4132-825b-f113dde24177"
authors = ["Reno <singularitti@outlook.com> and contributors"]
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
cif_api_jll = "6fcef0ae-1c05-5fc1-b206-1cf994addbad"

[compat]
CEnum = "0.4"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
